version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - taxi-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - taxi-network

  tracker-service:
    build:
      context: ../tracker-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - taxi-network
    depends_on:
      - kafka
      - cassandra

  real-time-map-service:
    build:
      context: ../real-time-map-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - taxi-network
    depends_on:
      - kafka
      - redis

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - taxi-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - taxi-network

networks:
  taxi-network:
    driver: bridge

